FROM registry.access.redhat.com/ubi9/nodejs-22:latest AS build

WORKDIR /opt/app-root/src

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-126:latest

USER root

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /opt/app-root/src/dist/ /opt/app-root/src/

RUN mkdir -p /tmp/client_temp /tmp/proxy_temp /tmp/fastcgi_temp /tmp/uwsgi_temp /tmp/scgi_temp && \
    chgrp -R 0 /opt/app-root /etc/nginx/nginx.conf && \
    chmod -R g=u /opt/app-root && \
    chmod g+r /etc/nginx/nginx.conf && \
    chgrp -R 0 /tmp && \
    chmod -R g+rwX /tmp

EXPOSE 8080

USER 1001

CMD ["nginx", "-g", "daemon off;"]
